name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Generate README file
        run: node index.js
                  git diff
                  git config --global user.email "kcihan.doruk@gmail.com"   
                  git config --global user.name "obsivium"
                  git add -A
                  git commit -m "Update README.md - Add new joke" || exit 0
                  git push
